version: 2

project_name: giteway

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

gomod:
  proxy: true

checksum:
  name_template: 'checksums.txt'

source:
  enabled: true

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip

snapshot:
  name_template: "{{ incpatch .Version }}-next"

sboms:
  - id: syft-archive
    artifacts: archive

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^.vscode"
      - "^.github"

dockers:
  - image_templates:
      - "galactiks/giteway:{{ .Tag }}"
      - "galactiks/giteway:v{{ .Major }}"
      - "galactiks/giteway:v{{ .Major }}.{{ .Minor }}"
      - "galactiks/giteway:latest"
      - "ghcr.io/thegalactiks/giteway:{{ .Tag }}"
      - "ghcr.io/thegalactiks/giteway:v{{ .Major }}"
      - "ghcr.io/thegalactiks/giteway:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/thegalactiks/giteway:latest"
    dockerfile: .docker/Dockerfile-goreleaser

docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: images
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"
